### ISSUE TITLE
OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory K:\AI\comfylAI\ComfyUI_windows_portable\ComfyUI.

### ISSUE THREAD

**Issue by osagem** [smthemex/ComfyUI_FoleyCrafter#9]
=> loading checkpoint 'K:/AI/comfylAI/ComfyUI_windows_portable/ComfyUI/models/foleycrafter/timestamp_detector.pth.tar'
=> loaded checkpoint 'K:/AI/comfylAI/ComfyUI_windows_portable/ComfyUI/models/foleycrafter/timestamp_detector.pth.tar' (epoch 23)
An error occurred while trying to fetch K:\AI\comfylAI\ComfyUI_windows_portable\ComfyUI\models\auffusion\auffusion-full-no-adapter: Error no file named diffusion_pytorch_model.safetensors found in directory K:\AI\comfylAI\ComfyUI_windows_portable\ComfyUI\models\auffusion\auffusion-full-no-adapter.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
An error occurred while trying to fetch K:\AI\comfylAI\ComfyUI_windows_portable\ComfyUI\models\auffusion\auffusion-full-no-adapter: Error no file named diffusion_pytorch_model.safetensors found in directory K:\AI\comfylAI\ComfyUI_windows_portable\ComfyUI\models\auffusion\auffusion-full-no-adapter.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
The config attributes {'decay': 0.9999, 'inv_gamma': 1.0, 'min_decay': 0.0, 'optimization_step': 100000, 'power': 0.6666666666666666, 'update_after_step': 0, 'use_ema_warmup': False} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
### unexpected keys: 0;
image_encoder is not loaded since `image_encoder_folder=None` passed. You will not be able to use `ip_adapter_image` when calling the pipeline with IP-Adapter.Use `ip_adapter_image_embeds` to pass pre-generated image embedding instead.
!!! Exception during processing !!! Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory K:\AI\comfylAI\ComfyUI_windows_portable\ComfyUI.
Traceback (most recent call last):
  File "K:\AI\comfylAI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\AI\comfylAI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\AI\comfylAI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "K:\AI\comfylAI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\AI\comfylAI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FoleyCrafter\FoleyCrafter_node.py", line 207, in main_loader
    image_encoder = CLIPVisionModelWithProjection.from_pretrained(ip_repo, subfolder="models/image_encoder").to(device)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\AI\comfylAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 3779, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory K:\AI\comfylAI\ComfyUI_windows_portable\ComfyUI.

**Comment by osagem** [comment]
problem found. IDM add "safe" in the file name. 
but the log error message said "Error no file named diffusion_pytorch_model.safetensors found in directory",  actually wrong file name is “model.safetensors”（wrong name is “model.safe.safetensors”） under image_encoder
